name: findtrackapp_v2
description: Práctica Integradora 2; 727272 - Cordero Hernández Marco Ricardo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  avatar_glow:
  equatable:
  flutter_bloc:
  flutter_launcher_icons:
  font_awesome_flutter:
  http:
  path_provider:
  permission_handler: ^9.2.0
  record: ^4.3.1
  url_launcher:
  # Firebase & Google
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_storage:
  flutterfire_ui:
  google_sign_in:

dev_dependencies:
  flutter_test:
    sdk: flutter  

flutter:  
  uses-material-design: true
  assets:
    - assets/